sudo: false
language: node_js
node_js:
  - "node"

cache: yarn

script:
  - ./node_modules/.bin/ng test --progress false --single-run --browsers ChromeHeadlessCustom

before_install:
  - nvm install 8
  - nvm use 8
